version: '3'
services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
      - "9400:9400"
    networks:
      internal_net:
    volumes:
      - dockerElasticVolume:/usr/share/elasticsearch/data
  
  kibana:
    image: docker.elastic.co/kibana/kibana:6.4.2
    container_name: kibana
    environment:
      - "ELASTICSEARCH_URL=http://elasticsearch:9200"
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    networks:
      - internal_net

  postgres:
    image: postgres
    container_name: postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=evendex
    volumes:
      - dockerPostgresVolume:/var/lib/postgresql/data
  
networks:
  internal_net:
    external: false

volumes:
  dockerElasticVolume:
    external: true
  dockerPostgresVolume:
    external: true
